[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'out'
libs = ['lib']
no_match_path = "contracts/*"
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 1
viaIR = false
eth_rpc_url = "YOUR_RPC_URL"

[profile.ci_test]
fork_block_number = 18963715

[profile.ci_sizes]
optimizer_runs = 1
test = 'DO_NOT_COMPILE'

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
runs = 1
max_test_rejects = 9_999_999
